### ISSUE TITLE
Error throwing whileSwitching between Admin and Login 

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#10]
It was normally navigating between the user and admin page with out the admin login credentials and it’s throwing an error while switching.

**Comment by arunandalam527** [comment]
#updated the Protected route functionality to the code 
`function ProtectedRoute({ element, adminRequired }) {`
  `if (adminRequired && auth.currentUser && auth.currentUser.email === 'adminmaps@gmail.com') {`
    `return element;`
  `} else if (!adminRequired && auth.currentUser) {`
    `return element;`
  `} else {`
    `return <Navigate to="/login" />;`
  `}`
`}`
