### ISSUE TITLE
The Coordinates are not rendering inside the Mapbox

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#11]
While adding the latitude and Longitude values through the admin portal the points are not rendering and throwing an error in the console

**Comment by arunandalam527** [comment]
###that error is throwing we have to parse the coordinates into float 
###here is the updated code 

`const coordinates = [parseFloat(formData.longitude), parseFloat(formData.latitude)];`
  `    const data = {`
    `    name: formData.name,`
      `  coordinates: coordinates,`
