### ISSUE TITLE
Showing the error in App.js file (Switch Command Not found)

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#12]
Throwing an error in App.js file at the switch command which is a part of react-router-dok npm package states that switch command is not found in the react-router-dom

**Comment by Pranayrajana** [comment]
it's because the React-router-dom npm package was updated to newer version 
here is the Updated code 
`import { Route, Routes, Navigate } from "react-router-dom";`
`<div className="App">`
  `    <div id="google_translate_element"></div>`
    `  <Routes>`
      `  {/* map component is userhome.js */}`
      `<Route path="/" element={<UserHome />} /> `
      `{/**/}`
      `</Routes>`
    `</div>`
