### ISSUE TITLE
Review Data is not adding to the firestore

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#14]
In the review.js file which is in the components folder when ther user give the data and clicks on submit button the data is not adding ot throwing a error in the console

**Comment by Pranayrajana** [comment]
it's because the React-router-dom npm package was updated to newer version 
here is the Updated code 
`import { Route, Routes, Navigate } from "react-router-dom";`
`<div className="App">`
  `    <div id="google_translate_element"></div>`
    `  <Routes>`
      `  {/* map component is userhome.js */}`
      `<Route path="/" element={<UserHome />} /> `
      `{/**/}`
      `</Routes>`
    `</div>`

**Comment by Pranayrajana** [comment]
it's because the React-router-dom npm package was updated to newer version 
here is the Updated code 
`import { Route, Routes, Navigate } from "react-router-dom";`
`<div className="App">`
  `    <div id="google_translate_element"></div>`
    `  <Routes>`
      `  {/* map component is userhome.js */}`
      `<Route path="/" element={<UserHome />} /> `
      `{/**/}`
      `</Routes>`
    `</div>`

**Comment by Pranayrajana** [comment]
I resolved  the bug in the POST method now the data is adding to the firestore data base
`const addTodo = async (e) => {`
`    e.preventDefault();`

    `try {`
      
      `const data = {`
        `name: formData.name,`
      `  email: formData.email,`
    `    review: formData.review,`
  `      rating: formData.rating,`
`      };`

      `const docRef = await addDoc(collection(db, 'reviews'), data);`
      `console.log('Document written with ID: ', docRef.id);`
      `alert("Data Added Successfully");`
      `fetchPost();`
     ` setFormData({`
        `name: '',`
        `email:'',`
        `review:'',`
        `rating: '1',`
      `});`
    `} catch (e) {`
    `  console.error('Error adding document: ', e);`
  `  }`
`  };`

**Comment by Pranayrajana** [comment]
I resolved  the bug in the POST method now the data is adding to the firestore data base
`const addTodo = async (e) => {`
`    e.preventDefault();`

    `try {`
      
      `const data = {`
        `name: formData.name,`
      `  email: formData.email,`
    `    review: formData.review,`
  `      rating: formData.rating,`
`      };`

      `const docRef = await addDoc(collection(db, 'reviews'), data);`
      `console.log('Document written with ID: ', docRef.id);`
      `alert("Data Added Successfully");`
      `fetchPost();`
     ` setFormData({`
        `name: '',`
        `email:'',`
        `review:'',`
        `rating: '1',`
      `});`
    `} catch (e) {`
    `  console.error('Error adding document: ', e);`
  `  }`
`  };`
