### ISSUE TITLE
The Registration forms lacks of input validation, allowing empty or invalid input validation  

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#3]
The registration form in Signup.js  does not validate user inputs for email and passwords it doesn’t possess any condition. if the users enter the email incorrectly still it’s going to register. which leads to empty or invalid entries, potentially causing issues with user registration

**Comment by nagasaiharireddyyendreddy** [comment]
#3
added the validation
`const handleSignup = async () => {`
  `  try {`
    `  await auth.createUserWithEmailAndPassword(email, password);`
      `alert("Registered Successfully");`
      `navigate('/');`
    `} catch (error) {`
    `  console.error(error);`
    `}`
  `};`
