### ISSUE TITLE
Missed import statements of the Mapbox-Gl library

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#4]
The code lacks the necessary import statement for the Mapbox GL library, which results in the 'mapboxgl' variable being undefined. This leads to errors when trying to use Mapbox GL functionality.

**Comment by nagasaiharireddyyendreddy** [comment]
added in mapbox.js
`import mapboxgl from 'mapbox-gl';`
`import MapboxDirections from '@mapbox/mapbox-gl-directions/dist/mapbox-gl-directions';`
`import '@mapbox/mapbox-gl-directions/dist/mapbox-gl-directions.css';`
and in the index.html also 
`<link
      href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css"
      rel="stylesheet"
    />`
