### ISSUE TITLE
Inside the Mapbox.js incorrect html structure for popup content 

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#5]
The code for generating popup content has an incorrect HTML structure. This can result in a broken or improperly formatted popup when a restroom marker is clicked.

**Comment by nagasaiharireddyyendreddy** [comment]
Modified the pop up content 
`.setPopup(new mapboxgl.Popup().setHTML(`<style>`
          `.mapboxgl-popup {`
            `max-width: 160px;`
            `max-height: 160px;`
          `}`
          
          `/* Style for the image carousel container */`
          `.image-carousel {`
            `display: flex;`
            `overflow: hidden;`
          `}`
          
          `/* Style for individual carousel slides (images) */`
          `.carousel-slide img{`
            `height:100px;`
            `width:100px;`
          `}`
          `</style><h3>${name}</h3><div class="image-carousel">`
          `<div class="carousel-slide">`
          `<a href="${image}" style="text-decoration:none;">`
            `<img src="${image}" alt="Image 1">`
            `</a>`
          `  </div>`
        `</div><p>${available}</p>`))`
