### ISSUE TITLE
Used The Older Firebase SDK commands for Authentication and Database Usage

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#6]
Initially we used the previous Version of firebase commands to access the Authentication and data base feature which results yields the error command not found error in console we used those commands all over their wherever they are required like for Signup.js , signin.js for authentication and database in other files like review and mapbox.js and review.js while fetching the details in testimonials .js file

**Comment by RamyaBanothu** [comment]
Updated the code as per the Firebase SDK V9 documentation 
here is the updated one :
in firebase.js 
`const app = firebase.initializeApp(firebaseConfig);`
`const db = getFirestore(app);`
`const auth = app.auth();`
`const analytics = getAnalytics();`
`const firebaseDb = getDatabase(app);`
`export  { auth, firebase , analytics , firebaseDb , db};`
and while applying the CRUD operaions in Database like 
`const querySnapshot = await getDocs(collection(db, "pins"));`
 `const newData = querySnapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id }));`
