### ISSUE TITLE
Error handling is missing in the data fetch function, making it challenging to diagnose issues.

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#7]
The fetchPost function in Review.js does not include proper error handling when fetching data. If there is an issue with data retrieval, it won't be handled, making it challenging to diagnose problems.

**Comment by RamyaBanothu** [comment]
Updated the fetchpost function
`const fetchPost = async () => {`
    `try {`
      `const querySnapshot = await getDocs(collection(db, 'reviews'));`
      `const newData = querySnapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id }));`
      `setFormDatas(newData);`
    `} catch (error) {`
   `   console.error('Error fetching reviews: ', error);`
    `}`
 ` };`
