### ISSUE TITLE
Missing error handling for Firebase initialization.

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#8]
There is no error handling for Firebase initialization in the code. This means that if there are any issues with initializing Firebase services, the code will not manage them correctly.

**Comment by RamyaBanothu** [comment]
updated the functionality 

`let app, db, auth, analytics, firebaseDb;`

`try {`
  `app = firebase.initializeApp(firebaseConfig);`
  `db = getFirestore(app);`
  `auth = app.auth();`
  `analytics = getAnalytics();`
  `firebaseDb = getDatabase(app);`
`} catch (error) {`
  `console.error('Firebase initialization error:', error);`
`}`
