### ISSUE TITLE
After adding the Data to the database through Admin portal . yields an error

### ISSUE THREAD

**Issue by dedeepyarao** [dedeepyarao/public_restroom_locator#9]
In the AdminHome.js file while the admin added all the data and clicks on submit the data is adding to database perfectly but that data remains in the textfield  even after submitting .

**Comment by arunandalam527** [comment]
updated the code to achieve the prevent default functionality
`fetchPost();`
      `setFormData({`
        `name: '',`
        `longitude: '',`
        `latitude: '',`
        `image: '',`
        `descriptionMon: '',`
        `descriptionTue: '',`
        `descriptionWed: '',`
        `descriptionThu: '',`
        `descriptionFri: '',`
        `descriptionSat: '',`
        `descriptionSun: '',`
        `available: 'available',`
        `babyChangingStation: 'Available',`
        `handicap: 'Yes',`
      `  rating: '1',`
      `});`

**Comment by arunandalam527** [comment]
updated the code to achieve the prevent default functionality
`fetchPost();`
      `setFormData({`
        `name: '',`
        `longitude: '',`
        `latitude: '',`
        `image: '',`
        `descriptionMon: '',`
        `descriptionTue: '',`
        `descriptionWed: '',`
        `descriptionThu: '',`
        `descriptionFri: '',`
        `descriptionSat: '',`
        `descriptionSun: '',`
        `available: 'available',`
        `babyChangingStation: 'Available',`
        `handicap: 'Yes',`
      `  rating: '1',`
      `});`
